### PR TITLE
Fix source uploading and refactor .travis.yml

### PR DESCRIPTION
**Pull request by ryanewel**
Same as aws-robotics/aws-robomaker-sample-application-cloudwatch#53

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by mm318 — APPROVED** [review]

**Comment by timrobotson** [comment]
New `travis-build@platform-notifications.robomaker.aws.a2z.com` email should also be added

**Review by timrobotson — CHANGES_REQUESTED** [review]
New travis-build@platform-notifications.robomaker.aws.a2z.com email should also be added so we get alarmed on build failures.

**Comment by ryanewel** [comment]
I think we should wait to uncomment the notification email until we've confirmed the pipeline is working

**Review by timrobotson — APPROVED** [review]

**Comment by timrobotson** [comment]
> I think we should wait to uncomment the notification email until we've confirmed the pipeline is working

Makes sense

**Pull request merged**
